{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-cleaner.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  {{- with .Values.serviceMonitor.endpoint }}
  - interval: {{ .interval }}
    port: metrics
    path: /metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- with .tlsConfig }}
    tlsConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .metricRelabelings }}
    metricRelabelings: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .relabelings }}
    relabelings: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.serviceMonitor.jobLabel }}
  jobLabel: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
    {{- if .Values.serviceMonitor.matchLabels }}
      {{- toYaml .Values.serviceMonitor.matchLabels | nindent 6 }}
    {{- else }}
      {{- include "k8s-cleaner.selectorLabels" . | nindent 6 }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}